server:
  port: 8080
  
spring:
  application:
    name: api-gateway
    
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/orders/**
            - id: inventory-service
              uri: lb://inventory-service
              predicates:
                - Path=/inventory/**
            
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
       
management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
